name: Publish Landing Page

on:
  workflow_dispatch:

  schedule:
    - cron: '*/60 * * * *'

jobs:
  build:
    timeout-minutes: 45
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: build & publish
      run: scripts/workflow-web.sh
      env:
        WEB_PATH: web/
        IPFS_API: ${{ secrets.IPFS_API }}
        FLY_ACCESS_TOKEN: ${{ secrets.FLY_ACCESS_TOKEN }}
        DOMAIN: ${{ secrets.DOMAIN }}
